export const userTableList = [
  {
    name: 'user',
    text: 'User',
    link: 'user',
    type: 'form',
    query: 'userForm',
    form: 'userForm',
  },
  {
    name: 'userBaseline',
    text: 'UserBaseline',
    link: 'user-baseline',
    type: 'form',
    query: 'userBaselineForm',
    form: 'userBaselineForm',
  },
  {
    name: 'drugEntry',
    text: 'DrugEntries',
    link: 'drug-entry',
    type: 'table',
    query: 'drugEntryTable',
    table: 'drugEntryTable',
  },
  {
    name: 'activityEntry',
    text: 'ActivityEntries',
    link: 'activity-entry',
    type: 'table',
    query: 'activityEntryTable',
    table: 'activityEntryTable',
  },
  {
    name: 'note',
    text: 'Notebook',
    link: 'note',
    type: 'table',
    query: 'noteTable',
    table: 'noteTable',
  },
  {
    name: 'foodEntry',
    text: 'FoodEntry',
    link: 'food-entry',
    type: 'table',
    query: 'foodEntryTable',
    table: 'foodEntryTable',
  },
  {
    name: 'diabetes',
    text: 'Diabetes',
    link: 'diabetes',
    type: 'table',
    query: 'diabetesTable',
    table: 'diabetesTable',
  },
  {
    name: 'lifestyle',
    text: 'Lifestyle',
    link: 'lifestyle',
    type: 'table',
    query: 'lifestyleTable',
    table: 'lifestyleTable',
  },
  {
    name: 'anthropometry',
    text: 'Anthropometry',
    link: 'anthropometry',
    type: 'table',
    query: 'anthropometryTable',
    table: 'anthropometryTable',
  },
  {
    name: 'cholesterol',
    text: 'Cholesterol',
    link: 'cholesterol',
    type: 'table',
    query: 'cholesterolTable',
    table: 'cholesterolTable',
  },
  {
    name: 'exercise',
    text: 'Exercise',
    link: 'exercise',
    type: 'table',
    query: 'exerciseTable',
    table: 'exerciseTable',
  },
  {
    name: 'calorie',
    text: 'Calorie',
    link: 'calorie',
    type: 'table',
    query: 'calorieTable',
    table: 'calorieTable',
  },
  {
    name: 'glucoseManual',
    text: 'GlucoseManual',
    link: 'glucose-manual',
    type: 'table',
    query: 'glucoseManualTable',
    table: 'glucoseManualTable',
  },
  {
    name: 'glucoseDevice',
    text: 'GlucoseDevice',
    link: 'glucose-device',
    type: 'table',
    query: 'glucoseDeviceTable',
    table: 'glucoseDeviceTable',
  },
  {
    name: 'insulinInjection',
    text: 'InsulinInjection',
    link: 'insulin-injection',
    type: 'table',
    query: 'insulinInjectionTable',
    table: 'insulinInjectionTable',
  },
  {
    name: 'kidney',
    text: 'Kidney',
    link: 'kidney',
    type: 'table',
    query: 'kidneyTable',
    table: 'kidneyTable',
  },
  {
    name: 'bloodPressure',
    text: 'BloodPressure',
    link: 'blood-pressure',
    type: 'table',
    query: 'bloodPressureTable',
    table: 'bloodPressureTable',
  },
  // {
  //   name: 'exercise',
  //   text: 'Exercise',
  //   link: 'exercise',
  //   type: 'table',
  //   query: 'exerciseTable',
  //   table: 'exerciseTable',
  // },
  {
    name: 'step',
    text: 'Step',
    link: 'step',
    type: 'table',
    query: 'stepTable',
    table: 'stepTable',
  },
];

export { queryList } from './queries';
export { formConfigList } from './forms';
export { tableConfigList } from './tables';
export { mutationList } from './mutations';
export { DropdownItems } from './dropdowns';
